### ISSUE TITLE
Documentation of key/parameter "profile" not consistent with code

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-backend#162]
In docs/notes_api.md it says 

If the key `profile` exists, it must have a value that is one of the three strings `"default_profile"`, `"test_profile_1"` and `"test_profile_2"`.

In the code (Zonemaster/WebBackend/Runner.pm) there is only a distinction between "test_profile_1" and default, which means that it is not possible to match "test_profile_2" with a separate profile/policy.

```
if ( $params->{profile} eq 'test_profile_1' ) {
            if (Zonemaster::WebBackend::Config->CustomProfilesPath()) {
                    Zonemaster->config->load_policy_file( Zonemaster::WebBackend::Config->CustomProfilesPath() . '/iana-profile.json' );
            }
            else {
                    Zonemaster->config->load_policy_file( 'iana-profile.json' );
            }
    }
```

**Comment by mtoma** [comment]
Hi Mats,

The Runner.pm implements only one "real" profile as this is the only one we have now.
In order to have this working properly the test_profile_X parameter needs to point to some real Zoneamster engine profile like it is the case for the test_profile_1 parameter.

The parameters test_profile_1 and test_profile_2 are here to follow the initial specification from Zoencheck which did have the option to switch between different test profile.
This is why we have this empty place holders. It makes switching of profiles possible but is not doing anything meaningful so far as we have only two profiles so far. The "default" profile that is the one used on the website zonemaster.net which is considered a reasonable testing profile for the vast majority and the IANA profile for which we use the test_profile_1 parameter value.

The test_profile_2 is here only to state "we can have more" if we need to.

Michal 

----- Original Message -----

**Comment by matsduf** [comment]
We will investigate support of profiles.

**Comment by sandoche2k** [comment]
Refer to #176

**Comment by sandoche2k** [comment]
@matsduf @mtoma 
For profile, rather the code should be like this:
1. When the API does not specify any profile object, the default_profile is called. 
2. In case, the user wants to use a specific profile, he should be first add a profile file (e.g.iana_profile.json)  in the specific folder  to the engine. 
3. When the API specifies a profile object, it should be via the file name (e.g. iana_profile), rather than test_profile_1 or test_profile_2.
4. The code should be something like this 
```
Zonemaster->config->load_policy_file( Zonemaster::WebBackend::Config->CustomProfilesPath() . 'file_name' );
```

**Comment by matsduf** [comment]
In the API call it would be flexible to permit file names instead of profile tags. If the GUI permits selecting profile, it should be a tag. Is the profile function ever used?

**Comment by pawal** [comment]
Using paths and filenames in APIs is a very bad security design, please avoid doing this.

**Comment by sandoche2k** [comment]
@matsduf Profile function is a requirement, and it has been implemented in Zonecheck. And i do agree with you on using tags rather than file names. 
@pawal 'file_name' is meant to be a variable and the value (e.g. iana_profile.json) should be retrieved from the profile object.

**Comment by matsduf** [comment]
> When the API specifies a profile object, it should be via the file name (e.g. iana_profile), rather than test_profile_1 or test_profile_2.

@sandoche2k, what is the difference between your suggestion and what we have today?

> Using paths and filenames in APIs is a very bad security design, please avoid doing this.

@pawal, I agree that using paths *and* filenames is bad. Using just filename referring to files in a predefined directory could be OK.

**Comment by sandoche2k** [comment]
@matsduf

Currently " Zonemaster->config->load_policy_file(
Zonemaster::WebBackend::Config->CustomProfilesPath() . '/iana-profile.json'
);" #The value of the filename

What i am prescribingfor " Zonemaster->config->load_policy_file(
Zonemaster::WebBackend::Config->CustomProfilesPath() . '/file_name' );
#Filename tag

**Comment by matsduf** [comment]
@sandoche2k, then I understood you correctly. You want the path to be set by the configuration, and then you should be able to use any filename in the API, and then a file of that name must exist in the path. I think the idea is OK, but I think we then should restrict allowable characters of the file name, e.g. "a-z", "A-Z", "0-9", ".", "_" and "-".

For GUI I think, if policy files are supported, then it should selected by type that is mapped to predefined file in the frontend.

**Comment by mtoma** [comment]
I would suggest here to allow to define the profiles tags freely in a specific secion of the config file.
The user would define a 'profile' => 'full filename' mapping and the backend would then just pick those from the config file.

----- Original Message -----

**Comment by matsduf** [comment]
@mtoma, why do you want to go via a profile tag instead of allowing the file name to be used?

**Comment by mtoma** [comment]
Because it assumes hard coding the directory where the profiles files are going to be taken from in the code.
Letting the user completely define what file is pointed by a profile tag seems to me more flexible and user friendly.

----- Original Message -----

**Comment by matsduf** [comment]
Both suggestions have its merits. Predefined tags pointing at files is flexible since you can put profile files in different directories. Allowing files in a predefined directory is flexible since you can add profile files without updating the configuration and restarting the backend.

@mtoma, if you want to have profile files in different directories, then your suggestion is the best.

**Comment by mtoma** [comment]
As I user I would probably like to avoid putting my profile files in the software installation directories especially as it is far from clear where the perl modules files are kept.
To add a tag you wouldn't even have to restart the backend as the config file is read again each time a parameter is retrieved.

----- Original Message -----

**Comment by mattias-p** [comment]
This issue can be closed. It regards inconsistency between documentation and code - see the title and description. notes_api.md doesn't exist anymore and API.md now clearly documents the relation between "test_profile_2" and "default_profile".

**Comment by matsduf** [comment]
Resolved with https://github.com/dotse/zonemaster-backend/commit/42dc14eca8b8ef62d4f621f84b9eca3705074c71
