### ISSUE TITLE
Preflight check: Domian existance test does not work

### ISSUE THREAD

**Issue by mtoma** [dotse/zonemaster-backend#19]
The delegated domain test tab should refuse to start testing the domain uai.fr

**Comment by sandoche2k** [comment]
I tested "uai.fr" in DNSCHECK. 

It did test and then say that the Nameservers are not found for the domain, which is appropriate. Actually the result of a DNS resolution for the domain is "SERVFAIL" and not "NXDOMAIN". 

I feel that zonemaster should behave similar to DNSCHECK rather than say "domain does not exist"

**Comment by mtoma** [comment]
You can test it in the undelegated tab Sandoche.

----- Original Message -----
