### ISSUE TITLE
Support for multiple policies and configs

### ISSUE THREAD

**Issue by matsduf** [dotse/zonemaster-backend#269]
Today, the Backend only supports two profile, one default profile and one alternative.  What is called "profile" in Backend, is called "policy" in CLI and engine. The Backend does not support choosing different Engine configurations.

1. To be consistent over Zonemaster, use the term "policy" in the Backend.
2. It should be possible to choose between multiple policies (i.e. Engine policies) (if available) from the API.
3. Add support in the API to choose between different Engine configs.
4. It should be possible to choose between multiple configs (if availble) from the API.
5. The selected policy or (Engine) config are to be used directly by the Engine.

Suggested solution:

1. Under "[ZONEMASTER]" in backend_config.ini add a keys "alternative_policies" and "alternative_configs".
2. Let "alternative_policies" point a directory to store the policies in.
3. If the policy (current "profile") in the API is given as xxx, then the file "<alternative_policies>/policy_xxx.json" should be used.
4. The policy names ("xxx") should be limited to something sensible, "a-zA-Z0-9-."
5. Let "alternative_configs" point a directory to store the configs in.
6. Add "config" to the API.
7. If the config in the API is given as xxx, then the file "<alternative_configs>/config_xxx.json" should be used.
8. The config names ("xxx") should be limited to something sensible, "a-zA-Z0-9-."

(Updated 2017-02-10)

**Comment by aabdnn** [comment]
Thanks for creating this issue @matsduf. I think that along with supporting multiple policies, the naming discrepancy (profile versus policy) should also be fixed, so that it's consistently called either "profile" or "policy" everywhere. I think "policy" makes sense, and it's probably easy to change it from "profile" to "policy" in the backend.

**Comment by pawal** [comment]
A profile was meant to be a combination of different configurations and policies to use. But if the feature is only meant to choose policy, it should be consistent to be called policy in all components.

(A policy by itself cannot disable certain tests to run.)

**Comment by aabdnn** [comment]
Thanks for the clarification @pawal. What you say makes sense, but it has not been properly implemented. If "profile" should choose a different configuration and policy, then I would expect that when a profile called "myprofile" is requested, the Zonemaster engine would look for something like "config_myprofile.json" and "policy_myprofile.json" in /etc/zonemaster. If either of these are missing, then Zonemaster would fall back to the default config or default policy. This would make Zonemaster truly flexible, in allowing it to run tests with several different profiles, for different purposes.

**Comment by aabdnn** [comment]
Hi @matsduf. I've just read your updated proposed solution, and I agree with it. It will provide a consistent solution.

**Comment by mattias-p** [comment]
I'll make a PR proposing a documentation update reflecting the above requirements.

**Comment by sandoche2k** [comment]
Also, if possible update the code in the backend.

**Comment by matsduf** [comment]
@sandoche2k said:

> I do agree with Anand, that it will be more simple if we can fusion the "config" and "policy" under the single file "profile", which in turn could be called from the CLI as
> 
> zonemaster-cli --profile file_name
> 
> And also from the backend by calling a single file.

The downside is that if you just want to change something in the config, then you have to create a different policy file too. Or do you want to join config and policy into one file?

I think we should have one concept. Either config+policy as two different files that you load with two different parameters in CLI or profile as one file that you load with one parameter in CLI.

And what we have in CLI should be the same as we have in Engine and Backend. Or else we get a mess.

**Comment by aabdnn** [comment]
Hi everyone. I'll give 2 suggestions:

1. Introduce the concept of a profile (with a corresponding --profile flag for the CLI and a "profile" key for the requests in the backend). In the absence of a profile, the Zonemaster engine should just load the default configs and policies, from the following paths, in this order, so that files in /etc/zonemaster take precedence over the defaults that ship with the package.

/etc/zonemaster/config.json
<installpath>/share/config.json
/etc/zonemaster/policy.json
<installpath>/share/policy.json

If a user specifies profile XXX, then the Zonemaster engine should try to load configs and policies from the following paths:

/etc/zonemaster/config_XXX.json
/etc/zonemaster/config.json
<installpath>/share/config.json
/etc/zonemaster/policy_XXX.json
/etc/zonemaster/policy.json
<installpath>/share/policy.json

In this case, the Zonemaster engine should try to load a config and a policy for profile XXX, but should just fall back to the default in sequence. A missing config_XXX or policy_XXX just means "use the default instead".

I like the idea of a profile because it's a neat logical concept that can permeate up to the GUI, where we may want to offer more than one test profile, and it translates neatly all the way to the engine.

2. My second suggestion is to drop "profile" completely everywhere, and just let the CLI and the backend allow specifying alternative "config" and "policy" options. Zonemaster engine should load these instead of the defaults. For both the CLI and backed, if the config or policy path is absolute, then the file should be read from that path. If relative, then it should be relative to /etc/zonemaster. And if the file does not exist, then Zonemaster engine should fall back to the defaults.

In both of these suggestions, the user has precise control over which files are read. The difference is conceptual. My personal preference is the first one, with a "profile". It still allows the user to override just config, or policy, or even both, given a certain profile. But it allows specifying just one option to the CLI and to the backend. And it's simple to pass it through from the GUI (or any other application).

I'm also tagging @vlevigneron here so he can see my comments.

**Comment by sandoche2k** [comment]
From an user perspective, i would have preferred a "profile" feature everywhere. 

For the default, fusion the existing "policy", "config", "filter" into one default file "profile". The engine should load the default profile file.

If an user wants to override the default, he copies the default "profile" file and modify with his preferences and provide a different profile name. 

From the CLI, he calls via 
```
zonemaster-cli --profile "filename"
```
Deprecate the "policy" and "config" option from the CLI. 

Similarly from the backend using the API. 

For the GUI, it will show the different existing profiles, and the user has the option to choose one from the drop down menu.

**Comment by mattias-p** [comment]
@aabdnn I think the filenames of the default policy and config files should be policy_default.json and config_default.json. That way it's possible to ask for the defaults explicitly. Apart from that I very much like your suggestions.

@sandoche2k Are filters a new feature? If so, please file a separate issue so we can keep the discussions separated.

Having the ability to specify explicit paths of individual configuration files (e.g. with --config and --profile) eases testing and debugging. For that reason I oppose the removal of the --config and --profile arguments from zonemaster-cli. A possible compromise is to have all three parameters where `--profile XXX` is a shorthand for `--config /etc/zonemaster/config_XXX.json --policy /etc/zonemaster/policy_XXX.json`.

**Comment by matsduf** [comment]
The primary default directory for config.json and policy.json is OS dependent and can be calculated by `perl -MFile::ShareDir=dist_dir -E 'say dist_dir( "Zonemaster" )'`. On Ubuntu it is `/usr/local/share/perl/5.18.2/auto/share/dist/Zonemaster`.

The secondary default directory is `/etc/zonemaster`. The tertiary default directory is `~/.zonemaster`.

@aabdnn wants to have profile as a bundle of config.json + policy.json. @sandoche2k suggests that those two are merged into one file, profile.json. My view is that as long as we keep them as separate files we should also refer to them as different files in Engine, CLI and Backend. I think that we only increase complexity by having two ways.

I think that the suggestion from @sandoche2k to merge config and policy into a profile is probably the preferred solution since we get a cleaner configuration of Zonemaster.

@aabdnn writes

> In this case, the Zonemaster engine should try to load a config and a policy for profile XXX, but should just fall back to the default in sequence. A missing config_XXX or policy_XXX just means "use the default instead".

I think that is a bad idea for Engine, CLI and Backend. If you misprint you rather have an error message than thinking that your are testing something else. And in GUI you should probably have a closed list to choose from.

**Comment by matsduf** [comment]
@mattias-p wrote

> Are filters a new feature? If so, please file a separate issue so we can keep the discussions separated.

Filtering is controlled by the config file.

**Comment by sandoche2k** [comment]
Will be solved by this : https://github.com/dotse/zonemaster/issues/498
