### ISSUE TITLE
Feature suggestion: listing profiles via API

### ISSUE THREAD

**Issue by helb** [dotse/zonemaster-backend#294]
I'm creating a new Javascript/React frontend for Zonemaster (communicating with `zonemaster-backend` directly, without the Perl webinterface, for use at @CZ-NIC).

It would be nice not to have the profiles [hardcoded](https://github.com/dotse/zonemaster-gui/search?utf8=%E2%9C%93&q=default_profile&type=) in templates, and get them from the backend instead.

I was thinking somehing like:

```json
{
  "jsonrpc": "2.0",
  "id": 2,
  "method": "list_profiles"
}
```
⬇️
```json
{  
   "jsonrpc": "2.0",
   "id": 2,
   "result": [  
      {  
         "id":"default_profile",
         "name":"Default profile"
      },
      {  
         "id":"test_profile_1",
         "name":"Test Profile 1"
      },
      {  
         "id":"test_profile_2",
         "name":"Test Profile 2"
      }
   ]
}
```

Maybe even with some basic description about what the particular profile does…

What do you guys think?

**Comment by matsduf** [comment]
Also see #269

**Comment by helb** [comment]
:+1: Sounds reasonable.

So i guess it would be `method: "list_policies"` or something similar…

**Comment by sandoche2k** [comment]
@helb Multiple configurable profiles will be supported in the backend. But, we feel that it is complex enough to list different profiles at the backend via the API, since we need to have description for each profile in different languages supported. 

On the positive note, we will make the GUI flexible enough to support multiple profiles with description in languages supported.
