### ISSUE TITLE
backend ignores language params in api responses

### ISSUE THREAD

**Issue by pamasse** [dotse/zonemaster-backend#315]
Hi,

When i do a domain check on the zonemaster.net gui, the response is always in English despite the language params in the request.

Here an example of the request : 
```
curl 'https://zonemaster.net/result?id=b70a2241d3e0fe8e&language=sv' -H 'Host: zonemaster.net' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2' --compressed -H 'Referer: https://zonemaster.net/test/b70a2241d3e0fe8e' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive'
```

**Comment by sandoche2k** [comment]
May relate to https://github.com/dotse/zonemaster-cli/issues/46

**Comment by mtoma** [comment]
Seems fixed in the version currently online on zonemaster.net

curl 'https://zonemaster.net/result?id=af17196dd5c4db97&language=fr' -H 'Host: zonemaster.net' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2' --compressed -H 'Referer: https://zonemaster.net/test/b70a2241d3e0fe8e' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive'

Returns french messages
