### ISSUE TITLE
PR #356 added insecure use of tmp files

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-backend#358]
This is a severe security issue.
See more here:
https://security.stackexchange.com/questions/34397/how-can-an-attacker-use-a-fake-temp-file-to-compromise-a-program

**Comment by mattias-p** [comment]
Discussion started here: https://github.com/dotse/zonemaster-backend/pull/356#discussion_r161172682

So the issue is the known filename under a world writable directory, correct? Piping the file from wget to apt-key instead of employing a temporary file would fix the issue. Did you have some other fix in mind?

**Comment by pawal** [comment]
Yes.

There are two writes to /tmp in PR #356:

1. wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm -O /tmp/mysql-community-release-el7-5.noarch.rpm
2. wget https://www.postgresql.org/media/keys/ACCC4CF8.asc -O /tmp/ACCC4CF8.asc

If you can do pipe, that is much better. You can also randomize file names, if pipe does not work.

**Comment by mattias-p** [comment]
Fixed by #359
