### ISSUE TITLE
Fix the "make install" target in Makefile

### ISSUE THREAD

**Issue by pawal** [dotse/zonemaster-backend#52]
See #48.

**Comment by mtoma** [comment]
Are we still planning to help packagers package the zonemaster backend and frontend modules or did something change and we are planning to offer a fully automatic installation?

**Comment by pawal** [comment]
Only packages can do fully automatic installation. A Makefile should only install the code properly. Make dist is not something that is very helpful for a package maintainer, Make install is

A package can be responsible for a fully automatic installation.

**Comment by cdybedahl** [comment]
Making the Perl modules that hold most of the source installable is not the same as a fully automated installation. It is both possible and highly desirable to make the Perl modules installable, while leaving things like database setup for scripts or manual intervention. For example, the dispatcher I wrote for my own use installs itself as a perfectly normal Perl module, has a command-line script to start and stop running, and that script has a flag to tell it to perform database installation.

But as it is now, at least the backend (I haven't looked at the GUI in detail yet) is both impossible to install as Perl modules due the choice of module names, and impossible to package for distributions due to its absolute requirement to reside in a directory with a particular string as part of its name.

**Comment by sandoche2k** [comment]
@mtoma I think this can be close too
